name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --build-arg USER_ID=$(id -u) -t my-snmp-image .
    - name: Run the Docker container
      run: docker run -u $(id -u) my-snmp-image /home/usnmp/snmp_test/run_test.sh
